---
- name: Create disk(s)
  command:
    cmd: |
      qemu-img create -f qcow2 -b {{ images[disk.image].path }} {{ disk.path }} {{ disk.size }}
  loop: "{{ vm.disks }}"
  loop_control:
    loop_var: disk

- name: Template XML
  shell:
    cmd: |
      virt-install \
      -n {{ vm.hostname }} \
      --description "{{ vm.description }}" \
      --os-type=Linux \
      --os-variant={{ vm.os }} \
      --ram={{ vm.resources.ram }} \
      --vcpus={{ vm.resources.cpu }} \
      {% for disk in vm.disks %}
      --disk path={{ disk.path }},device=disk \
      {% endfor %}
      --disk path={{ playbook_dir }}/data/vms/{{ vm.hostname }}/cloud-init.qcow2,device=cdrom \
      --boot hd \
      --graphics none \
      {% for network in vm.networks %}
      --network network={{ network }} \
      {% endfor %}
      --print-xml > {{ playbook_dir }}/data/vms/{{ vm.hostname }}/vm.xml
  register: vm_xml

- debug:
    msg: "{{ vm_xml }}"

- name: Define VM
  become: yes
  command:
    cmd: |
      virsh define {{ playbook_dir }}/data/vms/{{ vm.hostname }}/vm.xml