---
- name: Create disk(s)
  command:
    cmd: |
      qemu-img create -f qcow2 -b {{ images[disk.image].path }} {{ disk.path }} {{ disk.size }}
  loop: "{{ vm.disks }}"
  loop_control:
    loop_var: disk

- name: Template XML
  command:
    cmd: |
      virt-install \
      -n {{ vm.name }} \
      --description "{{ vm.description }}" \
      --os-type=Linux \
      --os-variant={{ vm.os }} \
      --ram={{ vm.resources.ram }} \
      --vcpus={{ vm.resources.cpu }}
      --disk path={{ playbook_dir }}/data/vm/{{ vm.name }}/cloudinit.qcow2,device=cdrom \
      {%- for disk in vm.disks %}
      --disk path={{ disk.path }},device=disk \
      {%- endfor %}
      --boot hd \
      --graphics none \
      {%- for network in vm.networks %}
      --network network={{ network }} \
      {%- endfor %}
      --print-xml
  register: vm_xml

- debug:
    msg: "{{ vm_xml }}"
- fail:

- name: Define VM
  command:
    cmd: |
      virsh define -
    stdin: "{{ vm_xml }}"