---
- name: add consul binary
  block:
    - name: create tmp dir
      tempfile:
        state: directory
      register: consul_tmp_dir
    - set_fact:
        consul_tmp_dir: "{{ consul_tmp_dir.path }}"
    - debug:
        msg: "{{ consul_tmp_dir }}"
    - name: download consul
      command:
        cmd: |
          curl {{ apps.consul.url }} -o {{ consul_tmp_dir }}/consul.zip
        warn: false
        creates: "{{ consul_tmp_dir }}/consul.zip"
    - name: unzip
      unarchive:
        src: "{{ consul_tmp_dir }}/consul.zip"
        remote_src: yes
        dest: "{{ consul_tmp_dir }}"
    - name: add consul to image
      block:
        - name: create mount point dir
          file:
            dest: "{{ consul_tmp_dir }}/root"
            state: directory
        - name: convert base image to raw
          command:
            cmd: |
              qemu-img convert -O raw {{ images[image.base].path }} {{ consul_tmp_dir }}/image.raw
        - name: find first sector
          parted:
            state: info
            device: "{{ consul_tmp_dir }}/image.raw"
            unit: B
          register: partition_info
        - set_fact:
            partition: "{{ partition_info.partitions | sort(attribute='size') | last }}"
        - name: Install consul
          block:
            - name: mount image
              become: yes
              # the mount module adds entries to fstab
              command: |
                mount {{ consul_tmp_dir }}/image.raw
                {{ consul_tmp_dir }}/root
                -o loop,offset={{ partition.begin | int }}
            - name: copy consul binary
              become: yes
              copy:
                src: "{{ consul_tmp_dir }}/consul"
                remote_src: yes
                dest: "{{ consul_tmp_dir }}/root/usr/bin/consul"
                mode: 0755
            - name: copy consul unit file
              become: yes
              copy:
                src: "files/consul.service"
                dest: "{{ consul_tmp_dir }}/root/etc/systemd/system/consul.service"
          always:
            - name: un-mount image
              become: yes
              mount:
                path: "{{ consul_tmp_dir }}/root"
                state: unmounted
        - name: convert raw image to qcow2
          become: yes
          command:
            cmd: |
              qemu-img convert -O qcow2 {{ consul_tmp_dir }}/image.raw {{ image.path }}
