---
all:
  vars:
    k8s:
      cri: containerd
      pod_cidr: 10.10.0.0/16
      kubeconfig:
        local_path: "{{ playbook_dir }}/.kubeconfig"
        # should be generated and encrypted
      bootstrap_token: um6dnt.vxkf890de9d0sy36
      join_addr: "master-0.service.consul:6443"
  hosts:
    master-0: &master-0
      ansible_host: master-0.service.consul
      ansible_ssh_private_key_file: ../vms/data/ssh
      ansible_user: ubuntu
    master-1: &master-1
      ansible_host: master-1.service.consul
      ansible_ssh_private_key_file: ../vms/data/ssh
      ansible_user: ubuntu

control_plane:
  hosts:
    master-0: *master-0
    master-1: *master-1
joining:
  hosts:
    master-1: *master-1
init:
  hosts:
    master-0: *master-0