- hosts: all
  roles:
    - name: 01_system
      tags:
        - system
    - name: 02_cri
      tags:
        - cri
    - name: 03_install
      tags:
        - install

- hosts: init
  roles:
    - name: 04_init
      tags:
        - init

- hosts: joining
  roles:
    - name: 05_join
      tags:
        - join
