---
- name: Download
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-armv7.tar.gz
    checksum: sha256:3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae
    dest: /tmp/node_exporter_1.0.1.tar.gz

- name: Unarchive
  become: yes
  unarchive:
    src: /tmp/node_exporter_1.0.1.tar.gz
    remote_src: yes
    dest: /tmp
    owner: root

- name: Copy
  become: yes
  copy:
    src: /tmp/node_exporter-1.0.1.linux-armv7/node_exporter
    remote_src: yes
    dest: /usr/bin
    mode: 755

- name: Install service
  become: yes
  copy:
    src: templates/node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
    mode: 0600

- name: Enable service
  become: yes
  service:
    name: node-exporter
    daemon_reload: yes
    enabled: true
