- name: Create vms directory
  file:
    dest: vms
    state: directory

- name: Create VM config files
  template:
    src: templates/vm.config
    dest: "vms/{{ item.role }}-{{ item.id }}.config"
  with_items: "{{ vms }}"

- name: Create VM cloud-init yaml files
  template:
    src: templates/vm.cloud-init.yml
    dest: "vms/{{ item.role }}-{{ item.id }}.cloud-init.yml"
  with_items: "{{ vms }}"
  register: ignition

- name: get user id
  become: yes
  user:
    name: squawk
  register: user

- name: Create iso from VM cloud-init yml files
  command:
    cmd: |
      docker run --rm -i
      --user {{ user.uid }}
      -v ${PWD}:/work --workdir /work
      cloud-utils:centos-7 cloud-localds vms/{{ item.role }}-{{ item.id }}.cloud-init.img vms/{{ item.role }}-{{ item.id }}.cloud-init.yml
  with_items: "{{ vms }}"
  when: "ignition.changed"

- name: Create VM disk
  command:
    cmd: "qemu-img create -f qcow2 -b {{ virt.storage.base_image }} vms/{{ item.role }}-{{ item.id }}.qcow2"
  with_items: "{{ vms }}"
