---
- name: Compile consul
  debug:
    msg: "TODO: Compile consul first (to ./files)"
  when: ansible_architecture not in ["amd64", "x86_64"]

- name: Create consul group
  become: yes
  group:
    name: consul

- name: Create consul user
  become: yes
  user:
    name: consul
    group: consul
    create_home: no

- name: Install consul
  become: yes
  copy:
    src: files/consul_{{ ansible_architecture }}
    dest: /usr/bin/consul
    mode: 0755

- name: Prepare directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
    - /usr/lib/systemd/system
    - /etc/consul.d
    - "{{ consul_data_dir }}"

- name: Install consul service
  become: yes
  copy:
    src: templates/consul.service
    dest: /usr/lib/systemd/system/consul.service
    mode: 0600

- name: Copy config file
  become: yes
  template:
    src: templates/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

- name: Enable consul service
  become: yes
  service:
    name: consul
    enabled: true
    daemon_reload: yes
    state: started
